FROM ubuntu

RUN apt update && apt upgrade -y 
RUN DEBIAN_FRONTEND=noninteractive apt install nginx wget php-cli php-fpm php-mysql php-json php-opcache php-mbstring php-xml php-gd php-curl -y
RUN wget "https://wordpress.org/latest.tar.gz" --directory-prefix=/tmp
RUN tar xf /tmp/latest.tar.gz --directory=/var/www/html
RUN chown -R www-data:www-data /var/www/html/wordpress
RUN chmod -R 755 /var/www/html/wordpress
COPY default /etc/nginx/sites-available

COPY entrypoint.sh /etc/entrypoint.sh
CMD ["/etc/entrypoint.sh"]
