# -*- mode: ruby -*-
# vi: set ft=ruby :

# ssh-keygen -t rsa -b 4096 -C "jenkins"

$jenkins_user_setup = <<SCRIPT
#!/bin/bash

function create_user {
  USER_EXISTS=0
  USERS=`getent passwd | cut -d":" -f1`
  
  for USER in $USERS;
  do
    if [[ $1 == $USER ]]; then
      echo "$1 user exists"
      USER_EXISTS=1
    fi
  done

  if [[ $USER_EXISTS -eq 0 ]]; then
    echo "Creating user: $1"
    adduser --disabled-password --gecos "" $1
  fi
}

function set_authorized_keys {
  if [[ ! -d /home/$1/.ssh ]]; then
    echo "Creating .ssh folder for $1 ssh access"
    mkdir /home/$1/.ssh
  fi
  
  if [[ ! -f /vagrant/keys/ansible.pub ]]; then
    echo "Make sure the vagrant folder is mounted and the file ansible.pub exists!"
    exit 1
  fi

  cat /vagrant/keys/ansible.pub > /home/$1/.ssh/authorized_keys

  chown -R $1:$1 /home/$1/.ssh
  chmod 600 /home/$1/.ssh/authorized_keys
}

function add_to_sudoers {

  if [ ! -f /etc/sudoers.d/$1 ]; then
    echo "Granting sudo access for user: $1"
    echo "$1 ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$1
  else
    echo "User has been already added to sudoers"
  fi
}

create_user "jenkins"
set_authorized_keys "jenkins"
add_to_sudoers "jenkins"

SCRIPT

$jenkins_setup_war_package = <<SCRIPT
#!/bin/bash
apt update
# instaleaza java
apt install openjdk-11-jre -y

#creeaza folder-ul unde instalam jenkins
mkdir /opt/jenkins

#descarca jenkins
wget https://get.jenkins.io/war/2.348/jenkins.war --directory-prefix=/opt/jenkins


#instaleaza plugin-uri
mkdir /opt/jenkins/plugins

wget -O /opt/jenkins/plugins/ace-editor.jpi                          https://updates.jenkins.io/latest/ace-editor.hpi                        
wget -O /opt/jenkins/plugins/ant.jpi                                 https://updates.jenkins.io/latest/ant.hpi                               
wget -O /opt/jenkins/plugins/antisamy-markup-formatter.jpi           https://updates.jenkins.io/latest/antisamy-markup-formatter.hpi         
wget -O /opt/jenkins/plugins/apache-httpcomponents-client-4-api.jpi  https://updates.jenkins.io/latest/apache-httpcomponents-client-4-api.hpi
wget -O /opt/jenkins/plugins/bootstrap5-api.jpi                      https://updates.jenkins.io/latest/bootstrap5-api.hpi                    
wget -O /opt/jenkins/plugins/bouncycastle-api.jpi                    https://updates.jenkins.io/latest/bouncycastle-api.hpi                  
wget -O /opt/jenkins/plugins/branch-api.jpi                          https://updates.jenkins.io/latest/branch-api.hpi                        
wget -O /opt/jenkins/plugins/build-timeout.jpi                       https://updates.jenkins.io/latest/build-timeout.hpi                     
wget -O /opt/jenkins/plugins/caffeine-api.jpi                        https://updates.jenkins.io/latest/caffeine-api.hpi                      
wget -O /opt/jenkins/plugins/checks-api.jpi                          https://updates.jenkins.io/latest/checks-api.hpi                        
wget -O /opt/jenkins/plugins/cloudbees-folder.jpi                    https://updates.jenkins.io/latest/cloudbees-folder.hpi                  
wget -O /opt/jenkins/plugins/command-launcher.jpi                    https://updates.jenkins.io/latest/command-launcher.hpi                  
wget -O /opt/jenkins/plugins/credentials-binding.jpi                 https://updates.jenkins.io/latest/credentials-binding.hpi               
wget -O /opt/jenkins/plugins/credentials.jpi                         https://updates.jenkins.io/latest/credentials.hpi                       
wget -O /opt/jenkins/plugins/display-url-api.jpi                     https://updates.jenkins.io/latest/display-url-api.hpi                   
wget -O /opt/jenkins/plugins/durable-task.jpi                        https://updates.jenkins.io/latest/durable-task.hpi                      
wget -O /opt/jenkins/plugins/echarts-api.jpi                         https://updates.jenkins.io/latest/echarts-api.hpi                       
wget -O /opt/jenkins/plugins/email-ext.jpi                           https://updates.jenkins.io/latest/email-ext.hpi                         
wget -O /opt/jenkins/plugins/font-awesome-api.jpi                    https://updates.jenkins.io/latest/font-awesome-api.hpi                  
wget -O /opt/jenkins/plugins/git-client.jpi                          https://updates.jenkins.io/latest/git-client.hpi                        
wget -O /opt/jenkins/plugins/git-server.jpi                          https://updates.jenkins.io/latest/git-server.hpi                        
wget -O /opt/jenkins/plugins/git.jpi                                 https://updates.jenkins.io/latest/git.hpi                               
wget -O /opt/jenkins/plugins/github-api.jpi                          https://updates.jenkins.io/latest/github-api.hpi                        
wget -O /opt/jenkins/plugins/github-branch-source.jpi                https://updates.jenkins.io/latest/github-branch-source.hpi              
wget -O /opt/jenkins/plugins/github.jpi                              https://updates.jenkins.io/latest/github.hpi                            
wget -O /opt/jenkins/plugins/gradle.jpi                              https://updates.jenkins.io/latest/gradle.hpi                            
wget -O /opt/jenkins/plugins/handlebars.jpi                          https://updates.jenkins.io/latest/handlebars.hpi                        
wget -O /opt/jenkins/plugins/jackson2-api.jpi                        https://updates.jenkins.io/latest/jackson2-api.hpi                      
wget -O /opt/jenkins/plugins/javax-activation-api.jpi                https://updates.jenkins.io/latest/javax-activation-api.hpi              
wget -O /opt/jenkins/plugins/javax-mail-api.jpi                      https://updates.jenkins.io/latest/javax-mail-api.hpi                    
wget -O /opt/jenkins/plugins/jaxb.jpi                                https://updates.jenkins.io/latest/jaxb.hpi                              
wget -O /opt/jenkins/plugins/jdk-tool.jpi                            https://updates.jenkins.io/latest/jdk-tool.hpi                          
wget -O /opt/jenkins/plugins/jjwt-api.jpi                            https://updates.jenkins.io/latest/jjwt-api.hpi                          
wget -O /opt/jenkins/plugins/jquery3-api.jpi                         https://updates.jenkins.io/latest/jquery3-api.hpi                       
wget -O /opt/jenkins/plugins/jsch.jpi                                https://updates.jenkins.io/latest/jsch.hpi                              
wget -O /opt/jenkins/plugins/junit.jpi                               https://updates.jenkins.io/latest/junit.hpi                             
wget -O /opt/jenkins/plugins/ldap.jpi                                https://updates.jenkins.io/latest/ldap.hpi                              
wget -O /opt/jenkins/plugins/mailer.jpi                              https://updates.jenkins.io/latest/mailer.hpi                            
wget -O /opt/jenkins/plugins/matrix-auth.jpi                         https://updates.jenkins.io/latest/matrix-auth.hpi                       
wget -O /opt/jenkins/plugins/matrix-project.jpi                      https://updates.jenkins.io/latest/matrix-project.hpi                    
wget -O /opt/jenkins/plugins/momentjs.jpi                            https://updates.jenkins.io/latest/momentjs.hpi                          
wget -O /opt/jenkins/plugins/okhttp-api.jpi                          https://updates.jenkins.io/latest/okhttp-api.hpi
wget -O /opt/jenkins/plugins/pam-auth.jpi                            https://updates.jenkins.io/latest/pam-auth.hpi
wget -O /opt/jenkins/plugins/pipeline-build-step.jpi                 https://updates.jenkins.io/latest/pipeline-build-step.hpi
wget -O /opt/jenkins/plugins/pipeline-github-lib.jpi                 https://updates.jenkins.io/latest/pipeline-github-lib.hpi
wget -O /opt/jenkins/plugins/pipeline-graph-analysis.jpi             https://updates.jenkins.io/latest/pipeline-graph-analysis.hpi
wget -O /opt/jenkins/plugins/pipeline-input-step.jpi                 https://updates.jenkins.io/latest/pipeline-input-step.hpi
wget -O /opt/jenkins/plugins/pipeline-milestone-step.jpi             https://updates.jenkins.io/latest/pipeline-milestone-step.hpi
wget -O /opt/jenkins/plugins/pipeline-model-api.jpi                  https://updates.jenkins.io/latest/pipeline-model-api.hpi
wget -O /opt/jenkins/plugins/pipeline-model-definition.jpi           https://updates.jenkins.io/latest/pipeline-model-definition.hpi
wget -O /opt/jenkins/plugins/pipeline-model-extensions.jpi           https://updates.jenkins.io/latest/pipeline-model-extensions.hpi
wget -O /opt/jenkins/plugins/pipeline-rest-api.jpi                   https://updates.jenkins.io/latest/pipeline-rest-api.hpi
wget -O /opt/jenkins/plugins/pipeline-stage-step.jpi                 https://updates.jenkins.io/latest/pipeline-stage-step.hpi
wget -O /opt/jenkins/plugins/pipeline-stage-tags-metadata.jpi        https://updates.jenkins.io/latest/pipeline-stage-tags-metadata.hpi
wget -O /opt/jenkins/plugins/pipeline-stage-view.jpi                 https://updates.jenkins.io/latest/pipeline-stage-view.hpi
wget -O /opt/jenkins/plugins/plain-credentials.jpi                   https://updates.jenkins.io/latest/plain-credentials.hpi
wget -O /opt/jenkins/plugins/plugin-util-api.jpi                     https://updates.jenkins.io/latest/plugin-util-api.hpi
wget -O /opt/jenkins/plugins/popper2-api.jpi                         https://updates.jenkins.io/latest/popper2-api.hpi
wget -O /opt/jenkins/plugins/resource-disposer.jpi                   https://updates.jenkins.io/latest/resource-disposer.hpi
wget -O /opt/jenkins/plugins/scm-api.jpi                             https://updates.jenkins.io/latest/scm-api.hpi
wget -O /opt/jenkins/plugins/script-security.jpi                     https://updates.jenkins.io/latest/script-security.hpi
wget -O /opt/jenkins/plugins/snakeyaml-api.jpi                       https://updates.jenkins.io/latest/snakeyaml-api.hpi
wget -O /opt/jenkins/plugins/ssh-credentials.jpi                     https://updates.jenkins.io/latest/ssh-credentials.hpi
wget -O /opt/jenkins/plugins/ssh-slaves.jpi                          https://updates.jenkins.io/latest/ssh-slaves.hpi
wget -O /opt/jenkins/plugins/sshd.jpi                                https://updates.jenkins.io/latest/sshd.hpi
wget -O /opt/jenkins/plugins/structs.jpi                             https://updates.jenkins.io/latest/structs.hpi
wget -O /opt/jenkins/plugins/timestamper.jpi                         https://updates.jenkins.io/latest/timestamper.hpi
wget -O /opt/jenkins/plugins/token-macro.jpi                         https://updates.jenkins.io/latest/token-macro.hpi
wget -O /opt/jenkins/plugins/trilead-api.jpi                         https://updates.jenkins.io/latest/trilead-api.hpi
wget -O /opt/jenkins/plugins/variant.jpi                             https://updates.jenkins.io/latest/variant.hpi
wget -O /opt/jenkins/plugins/workflow-aggregator.jpi                 https://updates.jenkins.io/latest/workflow-aggregator.hpi
wget -O /opt/jenkins/plugins/workflow-api.jpi                        https://updates.jenkins.io/latest/workflow-api.hpi
wget -O /opt/jenkins/plugins/workflow-basic-steps.jpi                https://updates.jenkins.io/latest/workflow-basic-steps.hpi
wget -O /opt/jenkins/plugins/workflow-cps-global-lib.jpi             https://updates.jenkins.io/latest/workflow-cps-global-lib.hpi
wget -O /opt/jenkins/plugins/workflow-cps.jpi                        https://updates.jenkins.io/latest/workflow-cps.hpi
wget -O /opt/jenkins/plugins/workflow-durable-task-step.jpi          https://updates.jenkins.io/latest/workflow-durable-task-step.hpi
wget -O /opt/jenkins/plugins/workflow-job.jpi                        https://updates.jenkins.io/latest/workflow-job.hpi
wget -O /opt/jenkins/plugins/workflow-multibranch.jpi                https://updates.jenkins.io/latest/workflow-multibranch.hpi
wget -O /opt/jenkins/plugins/workflow-scm-step.jpi                   https://updates.jenkins.io/latest/workflow-scm-step.hpi
wget -O /opt/jenkins/plugins/workflow-step-api.jpi                   https://updates.jenkins.io/latest/workflow-step-api.hpi
wget -O /opt/jenkins/plugins/workflow-support.jpi                    https://updates.jenkins.io/latest/workflow-support.hpi
wget -O /opt/jenkins/plugins/ws-cleanup.jpi                          https://updates.jenkins.io/latest/ws-cleanup.hpi

#seteaza own-ul 
chown -R jenkins:jenkins /opt/jenkins

#instaleaza jenkins ca si service
cp /vagrant/files/jenkins.service /lib/systemd/system
systemctl daemon-reload
systemctl enable jenkins
systemctl start jenkins

#instaleaza git si docker
apt install git -y
apt install docker -y

SCRIPT

$environment_setup = <<SCRIPT
#!/bin/bash
apt update
apt install docker -y

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "environment" do |lb|
    lb.vm.hostname = "environment"
    lb.vm.network "private_network", ip: "192.168.56.20"
    lb.vm.provision "shell", :inline => $jenkins_user_setup
    lb.vm.provision "shell", :inline => $environment_setup
    lb.vm.provider :virtualbox do |vb|
		vb.memory = 4096
		vb.cpus = 1
    end
  end
  config.vm.define "cicd" do |ap1|
    ap1.vm.hostname = "cicd"
    ap1.vm.network "private_network", ip: "192.168.56.10"
    ap1.vm.provision "shell", :inline => $jenkins_user_setup
    ap1.vm.provision "shell", :inline => $jenkins_setup_war_package
    ap1.vm.provider :virtualbox do |vb|
		vb.memory = 4096
		vb.cpus = 1
    end
  end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
